<a href="https://colab.research.google.com/github/srk-7/Online-Payment-Fraud-Detection/blob/main/mini_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
data = pd.read_csv('/content/onlinefraud.csv')
data

step      type     amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0          1   PAYMENT    9839.64  C1231006815      170136.00       160296.36   
1          1   PAYMENT    1864.28  C1666544295       21249.00        19384.72   
2          1  TRANSFER     181.00  C1305486145         181.00            0.00   
3          1  CASH_OUT     181.00   C840083671         181.00            0.00   
4          1   PAYMENT   11668.14  C2048537720       41554.00        29885.86   
...      ...       ...        ...          ...            ...             ...   
110808    11   PAYMENT   36633.75   C825489209       40317.31         3683.56   
110809    11   PAYMENT   19512.89    C57441272        3683.56            0.00   
110810    11   PAYMENT   21213.14  C1526823115           0.00            0.00   
110811    11  TRANSFER  266490.27    C23079109       92890.00            0.00   
110812    11  CASH_OUT  118777.61  C1510313227           0.00            0.00   

           nameDest  oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  
0       M1979787155             0.0            0.00      0.0             0.0  
1       M2044282225             0.0            0.00      0.0             0.0  
2        C553264065             0.0            0.00      1.0             0.0  
3         C38997010         21182.0            0.00      1.0             0.0  
4       M1230701703             0.0            0.00      0.0             0.0  
...             ...             ...             ...      ...             ...  
110808   M263628748             0.0            0.00      0.0             0.0  
110809  M1965409129             0.0            0.00      0.0             0.0  
110810  M1630743712             0.0            0.00      0.0             0.0  
110811  C1025031603             0.0       266490.27      0.0             0.0  
110812   C601893033       1019293.0             NaN      NaN             NaN  

[110813 rows x 11 columns]

In [ ]:
data.type.unique()

array(['PAYMENT', 'TRANSFER', 'CASH_OUT', 'DEBIT', 'CASH_IN'],
      dtype=object)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69858 entries, 0 to 69857
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   step            69858 non-null  int64  
 1   type            69858 non-null  object 
 2   amount          69858 non-null  float64
 3   nameOrig        69858 non-null  object 
 4   oldbalanceOrg   69858 non-null  float64
 5   newbalanceOrig  69858 non-null  float64
 6   nameDest        69858 non-null  object 
 7   oldbalanceDest  69858 non-null  float64
 8   newbalanceDest  69857 non-null  float64
 9   isFraud         69857 non-null  float64
 10  isFlaggedFraud  69857 non-null  float64
dtypes: float64(7), int64(1), object(3)
memory usage: 5.9+ MB


In [ ]:
data.size

768438

In [ ]:
data.shape

(69858, 11)

In [ ]:
data.columns

Index(['step', 'type', 'amount', 'nameOrig', 'oldbalanceOrg', 'newbalanceOrig',
       'nameDest', 'oldbalanceDest', 'newbalanceDest', 'isFraud',
       'isFlaggedFraud'],
      dtype='object')

In [ ]:
data.dtypes

step                int64
type               object
amount            float64
nameOrig           object
oldbalanceOrg     float64
newbalanceOrig    float64
nameDest           object
oldbalanceDest    float64
newbalanceDest    float64
isFraud           float64
isFlaggedFraud    float64
dtype: object

In [ ]:
data=data.dropna()
data

step      type    amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0         1   PAYMENT   9839.64  C1231006815       170136.0       160296.36   
1         1   PAYMENT   1864.28  C1666544295        21249.0        19384.72   
2         1  TRANSFER    181.00  C1305486145          181.0            0.00   
3         1  CASH_OUT    181.00   C840083671          181.0            0.00   
4         1   PAYMENT  11668.14  C2048537720        41554.0        29885.86   
...     ...       ...       ...          ...            ...             ...   
69852     9   PAYMENT  31125.16  C1901051677            0.0            0.00   
69853     9   PAYMENT  30681.62   C849962043            0.0            0.00   
69854     9   PAYMENT   2866.47   C258151288            0.0            0.00   
69855     9   PAYMENT   2926.88   C145336381            0.0            0.00   
69856     9   PAYMENT   3704.30  C1539334900            0.0            0.00   

          nameDest  oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  
0      M1979787155             0.0             0.0      0.0             0.0  
1      M2044282225             0.0             0.0      0.0             0.0  
2       C553264065             0.0             0.0      1.0             0.0  
3        C38997010         21182.0             0.0      1.0             0.0  
4      M1230701703             0.0             0.0      0.0             0.0  
...            ...             ...             ...      ...             ...  
69852   M552326592             0.0             0.0      0.0             0.0  
69853    M64549705             0.0             0.0      0.0             0.0  
69854  M1910014593             0.0             0.0      0.0             0.0  
69855  M1278169306             0.0             0.0      0.0             0.0  
69856  M1849245575             0.0             0.0      0.0             0.0  

[69857 rows x 11 columns]

In [ ]:
print("Total null in dataset:", data.isnull().sum().sum())
print("Total not a number in dataset:", data.isna().sum().sum())

Total null in dataset: 0
Total not a number in dataset: 0


In [ ]:
data.shape

(69857, 11)

In [ ]:
features = data[['step','amount','oldbalanceOrg','newbalanceOrig','oldbalanceDest','newbalanceDest']]
target = data['isFraud']
labels = data['isFraud']

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(features, target, test_size= 0.25, random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
st_x= StandardScaler()
x_train= st_x.fit_transform(x_train)
x_test= st_x.transform(x_test)

DECISION TREE

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier= DecisionTreeClassifier(criterion='entropy', random_state=0)
classifier.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [ ]:
ypred=classifier.predict(x_test)
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(ypred,y_test))
print(classification_report(ypred,y_test))
accuracy_score(ypred,y_test)

[[17428     7]
 [   14    16]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     17435
         1.0       0.70      0.53      0.60        30

    accuracy                           1.00     17465
   macro avg       0.85      0.77      0.80     17465
weighted avg       1.00      1.00      1.00     17465



0.9987975951903808

KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
clf= KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2 )
clf.fit(x_train, y_train)
yypred= clf.predict(x_test)
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(yypred,y_test))
print(classification_report(yypred,y_test))
accuracy_score(yypred,y_test)

[[17442    21]
 [    0     2]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     17463
         1.0       0.09      1.00      0.16         2

    accuracy                           1.00     17465
   macro avg       0.54      1.00      0.58     17465
weighted avg       1.00      1.00      1.00     17465



0.9987975951903808

NAIVE BAYES

In [ ]:
from sklearn.naive_bayes import GaussianNB
NaiveBayes = GaussianNB()
NaiveBayes.fit(x_train,y_train)
y_pred= classifier.predict(x_test)
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(y_pred,y_test))
print(classification_report(y_pred,y_test))
accuracy_score(y_pred,y_test)

[[17428     7]
 [   14    16]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     17435
         1.0       0.70      0.53      0.60        30

    accuracy                           1.00     17465
   macro avg       0.85      0.77      0.80     17465
weighted avg       1.00      1.00      1.00     17465



0.9987975951903808

RANDOM FOREST

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier= RandomForestClassifier(n_estimators= 5, criterion="entropy")
classifier.fit(x_train, y_train)
pred= classifier.predict(x_test)
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(pred,y_test))
print(classification_report(pred,y_test))
accuracy_score(pred,y_test)

[[17437    11]
 [    5    12]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     17448
         1.0       0.52      0.71      0.60        17

    accuracy                           1.00     17465
   macro avg       0.76      0.85      0.80     17465
weighted avg       1.00      1.00      1.00     17465



0.9990838820498139

SVM

In [ ]:
from sklearn.svm import SVC
SVM = SVC(gamma='auto')
SVM.fit(x_train,y_train)
p_val = SVM.predict(x_test)
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(p_val,y_test))
print(classification_report(p_val,y_test))
accuracy_score(p_val,y_test)

[[17442    23]
 [    0     0]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     17465
         1.0       0.00      0.00      0.00         0

    accuracy                           1.00     17465
   macro avg       0.50      0.50      0.50     17465
weighted avg       1.00      1.00      1.00     17465



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.9986830804466075

LOGISTIC REGRESSION

In [ ]:
from sklearn.linear_model import LogisticRegression
LogReg = LogisticRegression(random_state=2)
LogReg.fit(x_train,y_train)
predicted_values = LogReg.predict(x_test)
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(predicted_values,y_test))
print(classification_report(predicted_values,y_test))
accuracy_score(predicted_values,y_test)

[[17442    21]
 [    0     2]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     17463
         1.0       0.09      1.00      0.16         2

    accuracy                           1.00     17465
   macro avg       0.54      1.00      0.58     17465
weighted avg       1.00      1.00      1.00     17465



0.9987975951903808

XG BOOST

In [ ]:
import xgboost as xgb
XB = xgb.XGBClassifier()
XB.fit(x_train,y_train)
predicted_values = XB.predict(x_test)
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(predicted_values,y_test))
print(classification_report(predicted_values,y_test))
print(accuracy_score(predicted_values,y_test))

[[17440     8]
 [    2    15]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     17448
           1       0.65      0.88      0.75        17

    accuracy                           1.00     17465
   macro avg       0.83      0.94      0.87     17465
weighted avg       1.00      1.00      1.00     17465

0.9994274262811337


PREDICTION

In [ ]:
if  XB.predict([[2,9839.64,170136.0,160296.36,9839.64]])[0] == 0:
    print('not Fraud')
else: print('is Fraud')

not Fraud


In [ ]:
if  XB.predict([[3.2,402,65,52165]])[0] == 0:
    print('not Fraud')
else: print('is Fraud')

is Fraud
